Django/cs3450_group_project/workspace/cs3450_group_project/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('virtual_waitress.urls')),
    path('admin/', admin.site.urls),
]

Django/cs3450_group_project/workspace/virtual_waitress/urls.py
from django.urls import path

from . import views

app_name = "virtual_waitress"

urlpatterns = [
    # /virtual_waitress/manager/
    path('manager/', views.manager, name='manager'),

    # /virtual_waitress/cook/
    path('cook/', views.cook, name='cook'),

    path('update/entry/<int:entry_id>/', views.update_entry, name='entry_update'),
    path('update/order/<int:order_id>/', views.update_order, name='order_update'),

    # /virtual_waitress/review/
    path('review/', views.review, name='review'),

    # /virtual_waitress/inventory/
    path('inventory/', views.inventory, name='inventory'),

    # /virtual_waitress/
    path('', views.menu, name='menu'),

    # # returning to menu from any other page
    # path('menu/', views.menu, name='menu'),
]

Django/cs3450_group_project/workspace/virtual_waitress/models.py
import datetime
from django.db import models


# Create your models here.
class AllowedItems(models.Model):
    name = models.CharField("Item Name", max_length=250)
    units = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Allowable Inventory Item"


class Items(models.Model):
    itemType = models.ForeignKey(AllowedItems, on_delete=models.CASCADE)
    loc = models.CharField("Item Location", max_length=250)
    qty = models.PositiveIntegerField(default=0)
    cost = models.FloatField("Unit Cost", default=0)
    expiration = models.DateField("Expiration Date")
    vendor = models.CharField(max_length=250)

    def __str__(self):
        return str(self.itemType)

    class Meta:
        verbose_name = "Inventory Item"


class RestaurantName(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = "Restaurant Name"


class Order(models.Model):
    dateCreated = models.DateTimeField()
    ready = models.BooleanField(default=False)
    total = models.FloatField()
    orderNumber = models.IntegerField()
    table = models.CharField(default='counter', max_length=50)

    def __str__(self):
        return str(self.orderNumber)

    class Meta:
        verbose_name = "Order"


class Number(models.Model):
    number = models.IntegerField()

    def __str__(self):
        return str(self.number)

    class Meta:
        verbose_name = "Number"


class Menu(models.Model):
    menuItem = models.CharField(max_length=60)
    menuDescription = models.CharField(max_length=400)
    menuPrice = models.FloatField()

    def __str__(self):
        return str(self.menuItem)

    class Meta:
        verbose_name = "Menu"


class Review(models.Model):
    menuItem = models.ForeignKey(Menu, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    email = models.CharField(max_length=60)
    phone = models.CharField(max_length=60)
    starRating = models.FloatField()
    review = models.CharField(max_length=250)

    def __str__(self):
        return str(self.review)

    class Meta:
        verbose_name = "Review"


class Entry(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food = models.ForeignKey(Menu, on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=0)
    note = models.TextField("Customer Notes", blank=True)
    ready = models.BooleanField("Food Ready", default=False)
    foodName = models.CharField(max_length=60)

    def __str__(self):
        return str(self.qty) + "x " + str(self.food) + " for order " + str(self.order)

    class Meta:
        verbose_name = "Order Item"

Django/cs3450_group_project/workspace/virtual_waitress/forms.py
from django import forms
from .models import Review, Menu, Order, Entry
import datetime

class ReviewForm(forms.ModelForm):
    menuItem = forms.ModelChoiceField(Menu.objects.all())
    name = forms.CharField(
        max_length=60, 
        widget=forms.TextInput(
            attrs={'placeholder' : 'Enter your name',
            'display': 'block',
            'width': '100%',
            'padding': '0.375rem 0.5rem',
            'font-size': '0.9375rem',
            'line-height': '1.5',
            'color': '#495057',
            'background-color': '#fff',
            'background-clip': 'padding-box',
            'border': '1px solid #ccc',
            'border-radius': '0',
            'transition': 'border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out'}))
    email = forms.CharField(        
        max_length=60, 
        widget=forms.TextInput(
            attrs={'placeholder' : 'Enter your email',
            'display': 'block',
            'width': '100%',
            'padding': '0.375rem 0.5rem',
            'font-size': '0.9375rem',
            'line-height': '1.5',
            'color': '#495057',
            'background-color': '#fff',
            'background-clip': 'padding-box',
            'border': '1px solid #ccc',
            'border-radius': '0',
            'transition': 'border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out'}))
    phone = forms.CharField(        
        max_length=60, 
        widget=forms.TextInput(
            attrs={'placeholder' : 'Enter phone number',
            'display': 'block',
            'width': '100%',
            'padding': '0.375rem 0.5rem',
            'font-size': '0.9375rem',
            'line-height': '1.5',
            'color': '#495057',
            'background-color': '#fff',
            'background-clip': 'padding-box',
            'border': '1px solid #ccc',
            'border-radius': '0',
            'transition': 'border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out'}))
    starRating = forms.FloatField(
        max_value = 5, min_value = 1,
        widget=forms.NumberInput(
            attrs={'placeholder':'Enter 1-5',
            'display': 'block',
            'width': '100%',
            'padding': '0.375rem 0.5rem',
            'font-size': '0.9375rem',
            'line-height': '1.5',
            'color': '#495057',
            'background-color': '#fff',
            'background-clip': 'padding-box',
            'border': '1px solid #ccc',
            'border-radius': '0',
            'transition': 'border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out'}))
    review = forms.CharField(
        max_length=250,
        widget=forms.TextInput(
            attrs={'placeholder':'Enter a review',
            'display': 'block',
            'width': '100%',
            'padding': '0.375rem 0.5rem',
            'font-size': '0.9375rem',
            'line-height': '1.5',
            'color': '#495057',
            'background-color': '#fff',
            'background-clip': 'padding-box',
            'border': '1px solid #ccc',
            'border-radius': '0',
            'transition': 'border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out'}))

    class Meta:
        model = Review
        fields = ('menuItem', 'name', 'email', 'phone', 'review', 'starRating')

class NewMenuItem(forms.Form):
    menuItem = forms.CharField(max_length=60)
    menuDescription = forms.CharField(max_length=400)
    menuPrice = forms.FloatField()

class ChangePrice(forms.Form):
	badOrder = forms.IntegerField()
	newPrice = forms.FloatField()

#default=datetime.datetime.now()
class OrderForm(forms.Form):
    total = forms.FloatField()
    orderNumber = forms.IntegerField()
    table = forms.CharField()
    prefix = 'order'

class OrderItemForm(forms.Form):
    # Dynamically generate food, qty, note depending on the size of the menu

    food1 = forms.CharField()
    qty1 = forms.IntegerField()
    note1 = forms.CharField()
    food2 = forms.CharField()
    qty2 = forms.IntegerField()
    note2 = forms.CharField()
    food3 = forms.CharField()
    qty3 = forms.IntegerField()
    note3 = forms.CharField()
    food4 = forms.CharField()
    qty4 = forms.IntegerField()
    note4 = forms.CharField()
    food5 = forms.CharField()
    qty5 = forms.IntegerField()
    note5 = forms.CharField()
    prefix = 'orderItem'

#abandoned from cook using forms
class CompleteOrderItem(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ('ready',)

#abandoned from cook using forms
class CompleteOrder(forms.ModelForm):

    class Meta:
        model = Order
        fields = ('ready',)

Django/cs3450_group_project/workspace/virtual_waitress/templates/virtual_waitress/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block page-title %}Welcome to the Virtual Waitress{% endblock page-title %}
    </title>

    <link rel="stylesheet" href="https://bootswatch.com/4/spacelab/bootstrap.css"/>

    {% block page-style %}
        <style>
            .banner {
                font-weight: bold;
                margin: 2px;
                border: solid black;
                background-color: rgb(104, 155, 255);
            }
            #navbar_button:hover{
                background-color: #345276;
            }
        </style>
    {% endblock page-style %}

    {% block head-script %}

    {% endblock head-script %}

    {% block default-script %}
    {% endblock default-script %}

    {% block register-on-load-scripts %}
        <script>
            window.onload = function () {
                //loadBanner();
            }
        </script>
    {% endblock register-on-load-scripts %}

</head>
<body>


{% block nav-bar %}
    <nav class="navbar navbar-expand-lg" style="margin-bottom: 10px; padding: 0px; background-image: linear-gradient(#6d94bf, #446E9B 50%, #3e648d)">
        <a class="navbar-brand" href="{% url 'virtual_waitress:menu' %}">
            <div>
                <img src="{% static 'virtual_waitress/logo.png'%}" style="margin: 0px; width: 100px;" />
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                {% block navbar-menu %}
                    <li class="nav-item {% if activePage == 'menu' %}active{% endif %}">
                        <a id="navbar_button" class="nav-link" href="{% url 'virtual_waitress:menu' %}" style="color: white;">Menu
                            {% if activePage == 'menu' %}
                                <span class="sr-only">(current)</span>
                            {% endif %}
                        </a>
                    </li>
                {% endblock navbar-menu %}

                {% block navbar-manager %}
                    <li id="navbar_button" class="nav-item {% if activePage == 'manager' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'virtual_waitress:manager' %}" style="color: white">Manager
                            {% if activePage == 'manager' %}
                                <span class="sr-only">(current)</span>
                            {% endif %}
                        </a>
                    </li>
                {% endblock navbar-manager %}

                {% block navbar-cook %}
                    <li id="navbar_button" class="nav-item {% if activePage == 'cook' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'virtual_waitress:cook' %}" style="color: white">Cook
                            {% if activePage == 'cook' %}
                                <span class="sr-only">(current)</span>
                            {% endif %}
                        </a>
                    </li>
                {% endblock navbar-cook %}

                {% block navbar-review %}
                    <li id="navbar_button" class="nav-item {% if activePage == 'review' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'virtual_waitress:review' %}" style="color: white">Customer Review
                            {% if activePage == 'review' %}
                                <span class="sr-only">(current)</span>
                            {% endif %}
                        </a>
                    </li>
                {% endblock navbar-review %}
            </ul>
        </div>
    </nav>
{% endblock nav-bar %}

{% block central-content %}
    <main>
        <h1>Hello World!</h1>
    </main>
{% endblock central-content %}

{% block body-end-script %}

{% endblock body-end-script %}
</body>
</html>

Django/cs3450_group_project/workspace/virtual_waitress/templates/virtual_waitress/inventory.html
{% extends "./base.html" %} 

{% block page-title %}
Virtual Waitress Inventory
{% endblock page-title %}

{% block central-content %}

<div class="card border-primary mb-3" style="max-width: 95%;overflow: scroll;">
    <div class="card-header">Inventory Control 
            <button type="button" class="btn btn-link" style="float:right">Settings</button>
    </div>
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Check</th>
                    <th scope="col">Item Name</th>
                    <th scope="col">Location</th>
                    <th scope="col">QTY</th>
                    <th scope="col">Unit</th>
                    <th scope="col">Unit Cost</th>
                    <th scope="col">Expiration Date</th>
                    <th scope="col">Vendor</th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <th scope="row" style="display:flex; flex-direction:column; align-items:center;">
                        <input class="form-check-input" type="checkbox" value="" style="max-width: 20px;">
                    </th>
                    <th>
                        <input class="form-control" id="readOnlyInput" type="text" placeholder="Root Beer" readonly="" style="min-width: 250px;">
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="Wharehouse, Rack 4, Shelf 3" id="inputDefault" style="min-width: 250px;">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="43" id="inputDefault" style="min-width: 50px;">
                    </td>
                    <td>
                        <input class="form-control" id="readOnlyInput" type="text" placeholder="Liters" readonly="" style="min-width: 100px;">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="1.94" id="inputDefault" style="min-width: 75px;">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="12/31/9999" id="inputDefault" style="min-width: 120px;">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="A&W Inc." id="inputDefault" style="min-width: 250px;">
                    </td>
                </tr>

                <tr>
                    <th scope="row" style="display:flex; flex-direction:column; align-items:center;">
                        <input class="form-check-input" type="checkbox" value="">
                    </th>
                    <th>
                        <select class="form-control" id="exampleSelect1">
                            <option>Root Beer</option>
                            <option>Ice Cream</option>
                            <option>Burger Patties</option>
                            <option>Buns</option>
                            <option>Chicken</option>
                        </select>
                    </th>
                    <td>
                        <input type="text" class="form-control" placeholder="" id="inputDefault">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="" id="inputDefault">
                    </td>
                    <td>
                        <input class="form-control" id="readOnlyInput" type="text" placeholder="" readonly="">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="" id="inputDefault">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="" id="inputDefault">
                    </td>
                    <td>
                        <input type="text" class="form-control" placeholder="" id="inputDefault">
                    </td>
                </tr>

            </tbody>
        </table>

    </div>
</div>
<div style="display:flex; flex-direction:row; justify-content:space-evenly; min-width:95%">
    <button type="button" class="btn btn-success">Add New Row</button>
    <button type="button" class="btn btn-primary">Save Changes</button>
    <button type="button" class="btn btn-danger">Delete Item</button>
</div>
{% endblock central-content %}

Django/cs3450_group_project/workspace/virtual_waitress/templates/virtual_waitress/manager.html
{% extends "./base.html" %} {% block page-title %}Virtual Waitress Manager{% endblock page-title %} {% block page-style %}
{{ block.super }}
<style>
	.banner {
		font-weight: 900;
		margin: 2px;
		border-style: solid;
		border-color: black;
		background-color: rgb(102, 153, 255);
	}

	.FlexDiv {
		display: flex;
		flex-wrap: wrap;
		flex-direction: row;
	}

	.card {
		padding: 25px;
	}

	/* Tooltip container */

	.tooltip {
		position: relative;
		display: inline-block;
		border-bottom: 1px dotted black;
		/* If you want dots under the hoverable text */
	}

	/* Tooltip text */

	.tooltip .tooltiptext {
		visibility: visible;
		width: 120px;
		background-color: black;
		color: #fff;
		text-align: center;
		padding: 5px 0;
		border-radius: 6px;
		opacity: 0;

		/* Position the tooltip text - see examples below! */
		position: absolute;
		z-index: 1;
	}

	/* Show the tooltip text when you mouse over the tooltip container */

	.tooltip:hover .tooltiptext {
		visibility: visible;
	}
</style>
{% endblock page-style %} {% block register-on-load-scripts %}
<script>
	window.onload = function () {
		//loadBanner();
		//getMoney();
		getTableData();
		getEntryData();
		getMenu();
	}
</script> {% endblock register-on-load-scripts %} {% block head-script %}
<script>
	var salesMoney = 435.68;
	var dailySales = "Daily Sales: $" + salesMoney;
	var tableData = JSON.parse('{{ tableData|escapejs }}');
	var menuData = JSON.parse('{{ comboItemsMenu|escapejs }}');
	var entryData = JSON.parse('{{ entryData|escapejs }}');
	console.log(tableData);
	console.log(menuData);
	console.log(entryData);
	//var tableRow1 = [["0001", 13.50, "L4", 'N', 'N', "3:47"], ["0001", 13.50, "L4", 'N', 'N', "3:47"], ["0001", 13.50, "L4", 'N', 'N', "3:47"]
	//	, ["0001", 13.50, "L4", 'N', 'N', "3:47"], ["0001", 13.50, "L4", 'N', 'N', "3:47"], ["0001", 13.50, "L4", 'N', 'N', "3:47"]];
	var tableSize = 6;


	function getMoney() {
		document.getElementById("salesNumber").innerHTML = dailySales;
	}

	function getMenu() {
		var temp1 = document.getElementById("menuItem");
		for (var j = 0; j < menuData.length; j++) {
			var temp2 = document.createElement("option");
			temp2.text = menuData[j].menuItem;
			temp1.add(temp2);
		}
	}

	function tooltip(){
		var text = document.getElementById("tip");
		text.style.opacity = 1;
	}

	function tooltipOut(){
		var text = document.getElementById("tip");
		text.style.opacity = 0;
	}

	function getEntryData() {
		var temp1 = document.getElementById("table2");
		for (var k = 0; k < entryData.length; k++) {
			var temp2 = document.createElement("TR");
			temp1.appendChild(temp2);

			var temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].order_id;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].id;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].foodName;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].qty;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].note;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = entryData[k].ready;
			temp2.appendChild(temp3);
		}
	}

	function getTableData() {
		var temp1 = document.getElementById("table1");
		for (var j = 0; j < tableData.length; j++) {
			var temp2 = document.createElement("TR");
			temp1.appendChild(temp2);

			var temp3 = document.createElement("TD");
			temp3.innerHTML = tableData[j].orderNumber;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = tableData[j].id;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = tableData[j].total;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = tableData[j].table;
			temp2.appendChild(temp3);

			temp3 = document.createElement("TD");
			temp3.innerHTML = tableData[j].ready;
			temp2.appendChild(temp3);
			temp3 = document.createElement("TD");
			temp3.innerHTML = "00:00:00";
			temp2.appendChild(temp3);

		}
	}

</script> {% endblock head-script %} {% block central-content %}

<div class="card border-primary mb-3" style="max-width: 90%; margin:auto; margin-bottom: 10%; padding: 0px">
	<div class="card-header" style="width: 100%;">Current Orders</div>
	<div class="card-body">
		<div style="background-color: red;">
			<table id="table1" class="table table-primary">
				<tr class="table-info">
					<th>Order Number</th>
					<th>PK</th>
					<th>Price</th>
					<th>Table</th>
					<!-- As a waiter / waitress I need to identify which table / location an order relates to -->
					<!--<th>Needs Service?</th>-->
					<!-- As a waiter / waitress I need to know what locations / tables have service requests -->
					<th>Food Ready?</th>
					<th>Time Elapsed
						<th>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="card border-primary mb-3" style="max-width: 90%; margin:auto; margin-top: 10%; margin-bottom: 10%; padding: 0px;">
	<div class="card-header" style="width: 100%">In The Kitchen</div>
	<div class="card-body">
		<div style="background-color: red;">
			<table id="table2" class="table table-primary">
				<tr class="table-info">
					<th>PK</th>
					<th>ID</th>
					<th>Food</th>
					<th>qty</th>
					<th>note</th>
					<th>ready?</th>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="card border-primary mb-3" style="max-width: 90%; margin: auto; align-content: center; padding: 0px;">
	<div class="card-header">Manager Controls</div>
	<div class="card-body">
		<div class="FlexDiv" style="align-content: center">
			<!-- adjust order price -->
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px;">
				<form action="" method="post">
					{% csrf_token %}
					<div class="card-header" style="margin-bottom: 10px;">1. Change Order Price</div>
					<table>
						<tr>
							<th><label for="id_badOrder">Order (Use Order Number): </label></th>
							<th><label for="id_newPrice">New price: </label></th>
						</tr>
						<tr>
							<td><input type="number" name="badOrder" id="id_badOrder" required /></td>
							<td><input type="number" name="newPrice" id="id_newPrice" required step="any" /></td>
						</tr>
					</table>
				<input type="submit" name="adjustPriceSubmit" value="Submit">
				</form>
			</div>
			<!-- As a waiter / waitress, I would like to split or combine different bills -->
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px;">
				<form action="">
					<div class="card-header" style="margin-bottom: 10px;">2. Split Bill</div>
					<table>
						<tr>
							<th>
								<label for="blah2">Order Number:</label>
							</th>
							<td>
								<input type="text" name="splitBillOrderNumber">
							</td>
						</tr>
					</table>
					<input type="submit" name="splitBillSubmit" value="Submit" onmouseover="tooltip()" onmouseout="tooltipOut()">
					<div class="tooltip" style="opacity: unset">
						<span class="tooltiptext" id="tip">Not yet implemented</span>
					</div>
				</form>
			</div>

			<div class="card border-primary mb-3" style="width: 33%; padding: 0px; margin-bottom: 20px; padding-bottom: 20px">
				<div class="card-header" style="margin-bottom: 10px;">3. Add menu item</div>
				<!-- As a manager, I would like to delete, create, and manage menu items-->
				<form action="" method="post">
					{% csrf_token %}
					<table>
						<tr>
							<th>
								<label for="id_menuItem">Menu Item:</label>
							</th>
							<td>
								<input type="text" name="menuItem" maxlength="60" required id="id_menuItem" />
							</td>
						</tr>
						<tr>
							<th>
								<label for="id_menuDescription">Menu Description:</label>
							</th>
							<td>
								<input type="text" name="menuDescription" maxlength="400" required id="id_menuDescription" />
							</td>
						</tr>
						<tr>
							<th>
								<label for="id_menuPrice">Menu Price:</label>
							</th>
							<td>
								<input type="number" name="menuPrice" step="any" required id="id_menuPrice" />
							</td>
						</tr>

					</table>
					<input type="submit" name="newMenuItemSubmit" value="Submit">
				</form>
			</div>
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px; margin-bottom: 20px; padding-bottom: 20px">
				<form action="" method="post">
					{% csrf_token %}
					<div class="card-header" style="margin-bottom: 10px;">4. Remove Menu item</div>
					<table>
						<tr>
							<th>
								<label for="blah4">Target item:</label>
							</th>
							<td>
								<select name="removeItem" id="menuItem"></select>
							</td>
						</tr>
					</table>
					<input type="submit" name="removeItemSubmit" value="Submit">
				</form>
			</div>
			<!-- As a manager, I need to be able to override details about an open order (menu items, price, location, etc.) 
			
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px">
				<div class="card-header" style="margin-bottom: 10px;">3. Add menu item</div>
			
			-->
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px; margin-bottom: 20px; padding-bottom: 20px">
				<form action="" method="post">
					{% csrf_token %}
					<div class="card-header" style="margin-bottom: 10px;">5. Change table</div>
					<table>
						<tr>
							<th>
								<label for="id_oldOrder">Order Number:</label>
							</th>
							<td>
								<input type="number" name="oldOrder" required id="id_oldOrder" />
							</td>
						</tr>
						<tr>
							<th>
								<label for="id_newTable">New table:</label>
							</th>
							<td>
								<input type="text" name="newTable" maxlength="60" required id="id_newTable" />
							</td>
						</tr>
					</table>
					<input type="submit" name="adjustTableSubmit" value="Submit">
				</form>
			</div>
			<div class="card border-primary mb-3" style="width: 33%; padding: 0px; margin-bottom: 20px; padding-bottom: 20px">
				<form action="" method="post">
					{% csrf_token %}
					<div class="card-header" style="margin-bottom: 10px;">6. Remove Food From Order</div>
					<table>
						<tr>
							<th>
								<label for="blah6">Food ID Number:</label>
							</th>
							<td>
								<input type="number" name="changeOrder">
							</td>
						</tr>
					</table>
					<input type="submit" name="removeFoodSubmit" value="Submit">

					<!--<div class="card border-primary mb-3" style="width: 33%; padding: 0px;">
				<form action="" method="post">
					{% csrf_token %}
					<div class="card-header" style="margin-bottom: 10px;">1. Change Order Price</div>
					<table>
						<tr>
							<th><label for="id_badOrder">Order (Use Order Number): </label></th>
							<th><label for="id_newPrice">New price: </label></th>
						</tr>
						<tr>
							<td><input type="number" name="badOrder" id="id_badOrder" required /></td>
							<td><input type="number" name="newPrice" id="id_newPrice" required step="any" /></td>
						</tr>
					</table>
					<input type="submit" name="adjustPriceSubmit" value="Submit">
				</form>
				</div>
				-->


					<!-- this should probably just kick to menu with pre-populated fields -->
			</div>
		</div>



		{% endblock central-content %} {% block footer %}
		<footer>
			<h1>Code by Chaosreader and Froggy</h1>
		</footer>
		{% endblock footer %}